/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -a calculatoradaptor slavecalculator.xml
 *
 * qdbusxml2cpp is Copyright (C) 2022 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef CALCULATORADAPTOR_H
#define CALCULATORADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include <QtCore/qcontainerfwd.h>

/*
 * Adaptor class for interface com.blikoon.CalculatorInterface
 */
class CalculatorInterfaceAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.blikoon.CalculatorInterface")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.blikoon.CalculatorInterface\">\n"
"    <method name=\"multiplay\">\n"
"      <arg direction=\"out\" type=\"d\"/>\n"
"      <arg direction=\"in\" type=\"d\" name=\"x\"/>\n"
"      <arg direction=\"in\" type=\"d\" name=\"y\"/>\n"
"    </method>\n"
"    <method name=\"divide\">\n"
"      <arg direction=\"out\" type=\"d\"/>\n"
"      <arg direction=\"in\" type=\"d\" name=\"x\"/>\n"
"      <arg direction=\"in\" type=\"d\" name=\"y\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    CalculatorInterfaceAdaptor(QObject *parent);
    virtual ~CalculatorInterfaceAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    double divide(double x, double y);
    double multiplay(double x, double y);
Q_SIGNALS: // SIGNALS
};

#endif
