/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -p calculatorinterface slavecalculator.xml
 *
 * qdbusxml2cpp is Copyright (C) 2022 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "calculatorinterface.h"

/*
 * Implementation of interface class ComBlikoonCalculatorInterfaceInterface
 */

ComBlikoonCalculatorInterfaceInterface::ComBlikoonCalculatorInterfaceInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

ComBlikoonCalculatorInterfaceInterface::~ComBlikoonCalculatorInterfaceInterface()
{
}

